input:
    label: "SCZ"
    exposure_label: "CRP"
    id_exposure: "ebi-a-GCST90029070"
    id_outcome: "ieu-b-5102"
    type_outcome: "binary"
    prevalence_outcome: 0.0045
    # csv file contain trait information of the exposure and outcome
    info_exposure_outcome: NA

analysis:
    pop: "EUR"
    pval_instruments: 5e-8 # pvalue threshold for extracting instruments of the main exposure
    extract_traits:
        batch: ["ieu-a","ieu-b","ukb-b","ebi-a"]
        pval_traits: 1e-5 # pvalue threshold to retrieve traits
        min_snps: 5 # The number of minimum shared SNPs with IV of the main exposure
        type_exposure: "IEU" # exposure data type. IEU or local
        type_candidate_traits: "IEU" # candidate traits data type. IEU or local
        # file path of local exposure GWAS summary data; if not use local data, just write NA
        #file_path: "/nfs/turbo/sph-jvmorr/CRP_project/GWAS_summary_data/35459240-GCST90029070-EFO_0004458.h.tsv.gz"
        file_path: NA
        # csv file containing local candidate traits info; if not use local data, just write NA
        #df_candidate_traits: "example_candidate_info.csv"
        df_candidate_traits: NA
    quality_control:
        nsnp_cutoff: 1e6
        pop: "European"
        gender: "Males and Females"
        R2_cutoff: 0.85 # R2 cutoff for duplicated traits with X or Y
    string_filter:
        R2_cutoff: 0.95 # R2 cutoff for string similarity filtering
        extra_trait: "ukb-b-19953"
    strength_filter_initial:
        pval_threshold: 5e-8
        F_threshold: 5
        effect_size_cutoff: 0.1
    bidirection_mr:
        # Whether to adjust for extra traits in bidirection MR. If you want to do only UVMR, just set "None"
        extra_trait: "ukb-b-19953" # "None"
        #extra_trait: "None"
        min_instruments: 8 # minimum number of instruments for candidate traits
        effect_size_cutoff: 0.1 # Standardized effect size threshold
    downstream_filter:
        p: [0.05] # significant level for selecting upstream or downstream traits
        # which method to use for bidirection MR in downstream filtering step. If you use UVMR, choose either "MR_IVW","MR_GRAPPLE" or "MR_MRBEE"
        # If you use MVMR, choose either "MVMR_IVW","MVMR_GRAPPLE" or "MVMR_MRBEE"
        method: "MVMR_GRAPPLE"
        #method: "MR_GRAPPLE"
    unique_traits:
        R2_cutoff: 0.8
        method: "cluster" # filtering duplicate methods: sample_size, nsnp, cluster
        cluster_selection_method: ["n_inst","pvalue"]
    strength_filter:
        pval_threshold: 5e-8
        F_threshold: 5
        extra_traits: ["ukb-b-19953"]
        #extra_traits: "None"
    confounder_selection:
        seed: 1
        # If you add UVMR, only the main exposure will be included
        #method: ["UVMR","classic_Lasso","double_Lasso","marginal","stepwise","corrected_Lasso","double_corrected_Lasso"] # confounder selection method
        method: ["marginal","literature","UVMR"]
        # Methods for extracting instruments. If api fails, you can download and use local data.
        method_instruments: "Local" # "Local" or "API"
        r2_thresh: 0.001
        clump_kb: [10000]
        pval_threshold: 5e-8
        find_proxies: TRUE
        harmonise_strictness: 2
        lambda_type: ["min","1se"] # min or 1se
        radius_type: ["min","1se"] # min or 1se
        stepwise_method: ["forward"] # forward, backward or both
        marginal_p: 0.05
        maxits: 1000000
        literature_traits: ["ebi-a-GCST90029014","ebi-a-GCST006867"]
        # If you have extra traits for literature selection, generate file containing `id` and `location` for local files
        df_literature: "/nfs/turbo/sph-jvmorr/CRP_project/pipeline/data/df_literature.csv" # NA

    ldprune:
        r2_thresh: 0.001 # threshold for pairwise r^2 between variants
        clump_kb: [10000] # Maximum distance for pruning.
        ld_prioritization: "pvalue" # "pvalue" or "rank"
        ref_path: "/nfs/turbo/sph-jvmorr/ld_reference_files/1kg_plink/EUR" # Path to plink format reference data
        pthresh: 1

    estimate_R:
        type: ["ldsc","pval"] # ldsc or pval
        p_thresh: 0.05
        l2_dir: "/nfs/turbo/sph-jvmorr/ld_reference_files/ldsc_reference_files/eur_w_ld_chr/"
    
    MVMR_analysis:
        method: ["IVW","GRAPPLE","MRBEE","ESMR"]
        #method: ["IVW"]
        p_thresh_IVW: [5e-8]
        p_thresh_GRAPPLE: [1e-5,5e-8]
        p_thresh_MRBEE: [5e-8]
        p_thresh_ESMR: [5e-8]
        p_thresh_strength: 5e-8 # instrument threshold when calculating conditional F-stats
        pleio_p_thresh: [0,0.05] # pleiotropy threshold of MRBEE
        R_type: "ldsc" # either ldsc or pval
        effect_size_cutoff: 0.1 # Standardized effect size threshold
        
out:
    # Output data options:
    # data_dir: Directory to store results in the middle steps
    # gwas_dir: Where to store original gwas data
    # formatted_gwas_dir: Where do store formatted gwas data
    # output_dir: Where to store final results
    data_dir: "/nfs/turbo/sph-jvmorr/CRP_project/pipeline/data/"
    gwas_dir: "/nfs/turbo/sph-jvmorr/CRP_project/GWAS_summary_data/"
    output_dir: "results/"

